# Schema for the configuration files of the axxon module.
axxon.settings:
  type: config_object
  label: 'axxon settings'
  mapping:
    text:
      type: text
      label: 'Text'
    integer:
      type: integer
      label: 'Integer'
